---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^[0-9]{4}[-]{1}[0-9]{2}[-]{1}[0-9]{2}[a-z]{1}[0-9]{2}[-]{1}[0-9]{2}[-]{1}[0-9]{2}'
