---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: stg
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^stg-\d{1,2}\.\d{1,2}\.\d{1,2}'
---
