apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:  
    app: my-golang-deploy
spec: 
  selector: 
    mathcLabels:
      progect: golang   
  template:
    metadata:
      labels: 
        project: golang
    spec:
      containers: 
        - name: golang-web
          image: marina1327/task-01:latest
          ports:
            - containerPort: 8080 