apiVersion: v1
kind: Service 
metadata: 
  name: {{ .Values.service.name }}
  namespase: {{ .Values.namespase}}
spec: 
  selector:
    project: golang #select pods with this labels in template 
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.ports.port }} #port in loadbalanser 
      targetPort: {{ .Values.service.ports.targetPort }} #port in pods
